service: serverless-lambda-monorepo
frameworkVersion: '3'

provider:
  deploymentMethod: direct
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-3

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
