service: sns-service
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  deploymentMethod: direct
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-3'}

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
